name: PHP Tests

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello from PHP Tests
        run: |
          echo "Hello from PHP Tests!"
          sleep 50
